---
swagger: "2.0"
info:
  description: "Backend Challenge from Drixit [github.com/drixit/challenge, #Drixit](http://github.com/drixit/challenge)."
  version: "1.0.0"
  title: "Drixit Fullstack Challenge"
  contact:
    email: "juyagu@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/api/v0"
tags:
- name: "Users"
  description: "Everything about Users"
schemes:
- "https"
- "http"
paths:
  /authenticate:
    post:
      tags:
      - "users"
      summary: "Validate User Credentials"
      description: ""
      operationId: "authenticate"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "User object that is used to check credentials"
        required: true
        schema:
          $ref: "#/definitions/UserLogin"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "string"
        "400":
          description: "Invalid username/password supplied"
      x-swagger-router-controller: "Users"
  /users/me:
    get:
      tags:
      - "users"
      summary: "Get info about a user using a JWT"
      description: ""
      operationId: "userInfo"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "User object"
          schema:
            $ref: "#/definitions/User"
        "404":
          description: "User not found"
        "405":
          description: "Not allowed to GET user information"
      x-swagger-router-controller: "Users"
definitions:
  UserLogin:
    type: "object"
    properties:
      email:
        type: "string"
        format: "email"
      password:
        type: "string"
    example:
      password: "password"
      email: "email"
  User:
    type: "object"
    properties:
      id:
        type: "string"
      avatar:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
      name:
        type: "string"
      surname:
        type: "string"
      age:
        type: "number"
      role:
        type: "string"
    example:
      password: "password"
      role: "role"
      surname: "surname"
      name: "name"
      id: "id"
      avatar: "avatar"
      email: "email"
      age: 0.80082819046101150206595775671303272247314453125
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
